import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";

//get the Cinzel font from Google Fonts
const cinzel = Cinzel();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cinzel.className} antialiased`}>{children}</body>
    </html>
  );
}
